"""Marketplace catalog service.

Reads the public SPLENT index (features, SPLs, collisions) generated by
``splent marketplace:index`` and published as a static ``index.json``.

Resolution order:

1. In-memory cache (module-level, TTL ``CACHE_TTL_SECONDS``) — the service is
   re-instantiated on every ``service_proxy`` access, so the cache must live
   at module level to survive between requests.
2. Remote index at ``SPLENT_INDEX_URL`` (config/env, see config.py).
3. Local workspace fallback ``<WORKING_DIR>/.splent_cache/marketplace/index.json``
   when the network fails.
4. Last stale in-memory copy, then an empty index — the catalog degrades
   gracefully instead of raising.

Stdlib only (``urllib``), no third-party HTTP dependency.
"""

import json
import os
import time
import urllib.request

from flask import current_app, has_app_context

DEFAULT_INDEX_URL = "https://splent-io.github.io/splent_index/index.json"
# How long a fetched index is reused. Short on purpose: what a developer
# publishes has to show up here without anyone restarting anything, and a
# static JSON on a CDN is cheap to re-read. Products can raise it.
CACHE_TTL_SECONDS = 60
FETCH_TIMEOUT_SECONDS = 10
INDEX_SCHEMA = 1

EMPTY_INDEX = {"features": [], "spls": [], "collisions": []}

# Module-level TTL cache (see module docstring).
_cache = {"index": None, "fetched_at": 0.0}


class MarketplaceService:
    """Query the SPLENT marketplace index (features, SPLs, collisions)."""

    # ── index loading ─────────────────────────────────────────────────────

    def _index_url(self):
        if has_app_context():
            return current_app.config.get("SPLENT_INDEX_URL", DEFAULT_INDEX_URL)
        return os.getenv("SPLENT_INDEX_URL", DEFAULT_INDEX_URL)

    def _local_cache_path(self):
        working_dir = os.getenv("WORKING_DIR", os.getcwd())
        return os.path.join(working_dir, ".splent_cache", "marketplace", "index.json")

    def _fetch_remote(self):
        with urllib.request.urlopen(
            self._index_url(), timeout=FETCH_TIMEOUT_SECONDS
        ) as response:
            return json.loads(response.read().decode("utf-8"))

    def _read_local(self):
        with open(self._local_cache_path(), encoding="utf-8") as fh:
            return json.load(fh)

    @staticmethod
    def _is_index(data):
        """True when *data* has the shape of a marketplace index document.

        Both sources are untrusted JSON (a remote URL, an editable local
        cache): a parseable document with the wrong shape must be treated
        exactly like a missing one, or every catalog page 500s for the whole
        TTL. Same contract as the configurator's ``_is_index``.
        """
        if not isinstance(data, dict) or data.get("schema") != INDEX_SCHEMA:
            return False
        return all(
            isinstance(data.get(key) or [], list)
            for key in ("features", "spls", "collisions")
        )

    @staticmethod
    def _normalize_index(index):
        """Drop non-dict list entries and default missing feature keys.

        A partially corrupt entry (``collisions: ["bad"]``) or a feature
        without ``provides``/``requires`` must degrade to an incomplete card,
        never to a 500 in the templates.
        """
        for key in ("features", "spls", "collisions"):
            index[key] = [
                entry for entry in (index.get(key) or []) if isinstance(entry, dict)
            ]
        for feature in index["features"]:
            feature["provides"] = (
                feature.get("provides")
                if isinstance(feature.get("provides"), dict)
                else {}
            )
            feature["requires"] = (
                feature.get("requires")
                if isinstance(feature.get("requires"), dict)
                else {}
            )
            for list_key in ("tags", "used_by"):
                if not isinstance(feature.get(list_key), list):
                    feature[list_key] = []
        return index

    def _cache_ttl(self) -> int:
        if has_app_context():
            return int(
                current_app.config.get("SPLENT_INDEX_TTL_SECONDS", CACHE_TTL_SECONDS)
            )
        return CACHE_TTL_SECONDS

    def _read_valid(self, reader):
        """Read one source, or None when it is unusable.

        Both sources are untrusted: a remote URL that may be down and a
        local file anyone can edit. A malformed document is treated as
        absent so the other source can win.
        """
        try:
            data = reader()
        except Exception:
            return None
        return data if self._is_index(data) else None

    @staticmethod
    def _newer_index(local, remote):
        """The more recently generated of two indexes.

        An index with no generated_at loses to one that has it, and ties go
        to the remote: the published index is the shared answer, so it is
        the better default when there is nothing to choose between them.
        """
        if local is None:
            return remote
        if remote is None:
            return local
        if (remote.get("generated_at") or "") >= (local.get("generated_at") or ""):
            return remote
        return local

    def _load_index(self, force=False):
        """Return the index dict, honouring the TTL cache and fallbacks."""
        now = time.time()
        if (
            not force
            and _cache["index"] is not None
            and now - _cache["fetched_at"] < self._cache_ttl()
        ):
            return _cache["index"]

        # Whichever index was generated later wins.
        #
        # The rule used to be "a local workspace cache means a development
        # checkout, so local is the truth". That holds for a laptop, and it
        # is wrong for a deployment that runs from a workspace: the server
        # then looks like a checkout and serves a local copy that never
        # expires, so a freshly published feature or product line simply
        # never appears. Comparing generated_at gives both what they want
        # with nothing to configure: a developer who just ran
        # marketplace:index gets their own build, and a server whose copy is
        # older than the published one follows the published one.
        local = self._read_valid(self._read_local)
        remote = self._read_valid(self._fetch_remote)
        index = self._newer_index(local, remote)
        if index is None:
            # Neither source is usable: keep serving the last good copy
            # rather than emptying the catalogue.
            if _cache["index"] is not None:
                return _cache["index"]
            return EMPTY_INDEX

        index = self._normalize_index(index)
        _cache["index"] = index
        _cache["fetched_at"] = now
        return index

    # ── queries ───────────────────────────────────────────────────────────

    def index(self):
        """The raw index document (features, spls, collisions, metadata)."""
        return self._load_index()

    def all_features(self):
        """Every feature in the index, sorted by short name."""
        features = self._load_index().get("features") or []
        return sorted(features, key=lambda f: f.get("short") or "")

    def find(self, short):
        """A single feature by its short name (or repo name). None if absent."""
        for feature in self.all_features():
            if feature.get("short") == short or feature.get("repo") == short:
                return feature
        return None

    # ── optional Elasticsearch (soft dependency) ─────────────────────────

    ES_INDEX_NAME = "marketplace_features"

    def _es_service(self):
        """The ElasticsearchService when installed and reachable, else None.

        Soft dependency: the catalog searches in memory without it and
        transparently upgrades to full-text search when the elasticsearch
        feature is part of the product.
        """
        try:
            from splent_framework.services.service_locator import service_proxy

            svc = service_proxy("ElasticsearchService")
            return svc if svc.available() else None
        except Exception:
            return None

    def _es_ensure_indexed(self, es, index_doc):
        """Index the catalog once per index generation (cheap: ~30 docs)."""
        generation = index_doc.get("generated_at") or ""
        if _cache.get("es_indexed_for") == generation:
            return
        es.ensure_index(self.ES_INDEX_NAME)
        for f in index_doc.get("features") or []:
            es.index_document(
                self.ES_INDEX_NAME,
                f["short"],
                {
                    "short": f.get("short"),
                    "repo": f.get("repo"),
                    "description": f.get("description"),
                    "tags": f.get("tags") or [],
                    "archetype": f.get("archetype"),
                    "category": f.get("category"),
                },
            )
        # Elasticsearch is near-real-time: without an explicit refresh the
        # documents just indexed are invisible to the search that follows in
        # this same request (a fresh index would answer "no results" for ~1s).
        # ~30 docs, so the refresh is cheap. getattr keeps older
        # ElasticsearchService versions (without refresh_index) working.
        refresh = getattr(es, "refresh_index", None)
        if callable(refresh):
            refresh(self.ES_INDEX_NAME)
        _cache["es_indexed_for"] = generation

    def _es_search_shorts(self, query):
        """Ranked shorts for a free-text query, or None to use the fallback."""
        es = self._es_service()
        if es is None:
            return None
        try:
            self._es_ensure_indexed(es, self._load_index())
            result = es.search(
                self.ES_INDEX_NAME,
                {
                    "query": {
                        "multi_match": {
                            "query": query,
                            "fields": ["short^3", "repo^2", "tags^2", "description"],
                            "fuzziness": "AUTO",
                        }
                    },
                    "size": 100,
                },
            )
            return [h["_source"]["short"] for h in result.get("hits", [])]
        except Exception:
            return None

    def search(self, query=None, category=None, archetype=None):
        """Features filtered by free-text query, category and/or archetype.

        The query matches (case-insensitive) against short name, repo,
        description and tags. Category and archetype are exact matches.
        """
        results = self.all_features()
        if archetype:
            results = [f for f in results if f.get("archetype") == archetype]
        if category:
            results = [f for f in results if f.get("category") == category]
        if query:
            ranked = self._es_search_shorts(query.strip())
            if ranked is not None:
                by_short = {f["short"]: f for f in results}
                return [by_short[s] for s in ranked if s in by_short]
            needle = query.strip().lower()
            results = [
                f
                for f in results
                if needle in (f.get("short") or "").lower()
                or needle in (f.get("repo") or "").lower()
                or needle in (f.get("description") or "").lower()
                or any(needle in (tag or "").lower() for tag in (f.get("tags") or []))
            ]
        return results

    def spls(self):
        """The SPLs described in the index."""
        return self._load_index().get("spls") or []

    def collisions(self):
        """All provide-collisions detected across the indexed features."""
        return self._load_index().get("collisions") or []

    def collisions_for(self, short):
        """Collisions that involve the given feature short name."""
        return [c for c in self.collisions() if short in (c.get("features") or [])]

    def archetypes(self):
        """Distinct archetypes present in the index (for filter controls)."""
        return sorted(
            {f.get("archetype") for f in self.all_features() if f.get("archetype")}
        )

    def categories(self):
        """Distinct categories present in the index (for filter controls)."""
        return sorted(
            {f.get("category") for f in self.all_features() if f.get("category")}
        )
