"""Marketplace catalog service.

Reads the public SPLENT index (features, SPLs, collisions) generated by
``splent marketplace:index`` and published as a static ``index.json``.

Resolution order:

1. In-memory cache (module-level, TTL ``CACHE_TTL_SECONDS``) — the service is
   re-instantiated on every ``service_proxy`` access, so the cache must live
   at module level to survive between requests.
2. Remote index at ``SPLENT_INDEX_URL`` (config/env, see config.py).
3. Local workspace fallback ``<WORKING_DIR>/.splent_cache/marketplace/index.json``
   when the network fails.
4. Last stale in-memory copy, then an empty index — the catalog degrades
   gracefully instead of raising.

Stdlib only (``urllib``), no third-party HTTP dependency.
"""

import json
import os
import time
import urllib.request

from flask import current_app, has_app_context

DEFAULT_INDEX_URL = "https://splent-io.github.io/splent_index/index.json"
CACHE_TTL_SECONDS = 300
FETCH_TIMEOUT_SECONDS = 10

EMPTY_INDEX = {"features": [], "spls": [], "collisions": []}

# Module-level TTL cache (see module docstring).
_cache = {"index": None, "fetched_at": 0.0}


class MarketplaceService:
    """Query the SPLENT marketplace index (features, SPLs, collisions)."""

    # ── index loading ─────────────────────────────────────────────────────

    def _index_url(self):
        if has_app_context():
            return current_app.config.get("SPLENT_INDEX_URL", DEFAULT_INDEX_URL)
        return os.getenv("SPLENT_INDEX_URL", DEFAULT_INDEX_URL)

    def _local_cache_path(self):
        working_dir = os.getenv("WORKING_DIR", os.getcwd())
        return os.path.join(working_dir, ".splent_cache", "marketplace", "index.json")

    def _fetch_remote(self):
        with urllib.request.urlopen(
            self._index_url(), timeout=FETCH_TIMEOUT_SECONDS
        ) as response:
            return json.loads(response.read().decode("utf-8"))

    def _read_local(self):
        with open(self._local_cache_path(), encoding="utf-8") as fh:
            return json.load(fh)

    def _load_index(self, force=False):
        """Return the index dict, honouring the TTL cache and fallbacks."""
        now = time.time()
        if (
            not force
            and _cache["index"] is not None
            and now - _cache["fetched_at"] < CACHE_TTL_SECONDS
        ):
            return _cache["index"]

        try:
            index = self._fetch_remote()
        except Exception:
            try:
                index = self._read_local()
            except (OSError, ValueError):
                # No network and no local copy: keep serving the stale
                # in-memory index if we ever had one.
                if _cache["index"] is not None:
                    return _cache["index"]
                return EMPTY_INDEX

        _cache["index"] = index
        _cache["fetched_at"] = now
        return index

    # ── queries ───────────────────────────────────────────────────────────

    def index(self):
        """The raw index document (features, spls, collisions, metadata)."""
        return self._load_index()

    def all_features(self):
        """Every feature in the index, sorted by short name."""
        features = self._load_index().get("features") or []
        return sorted(features, key=lambda f: f.get("short") or "")

    def find(self, short):
        """A single feature by its short name (or repo name). None if absent."""
        for feature in self.all_features():
            if feature.get("short") == short or feature.get("repo") == short:
                return feature
        return None

    def search(self, query=None, category=None, archetype=None):
        """Features filtered by free-text query, category and/or archetype.

        The query matches (case-insensitive) against short name, repo,
        description and tags. Category and archetype are exact matches.
        """
        results = self.all_features()
        if archetype:
            results = [f for f in results if f.get("archetype") == archetype]
        if category:
            results = [f for f in results if f.get("category") == category]
        if query:
            needle = query.strip().lower()
            results = [
                f
                for f in results
                if needle in (f.get("short") or "").lower()
                or needle in (f.get("repo") or "").lower()
                or needle in (f.get("description") or "").lower()
                or any(needle in (tag or "").lower() for tag in (f.get("tags") or []))
            ]
        return results

    def spls(self):
        """The SPLs described in the index."""
        return self._load_index().get("spls") or []

    def collisions(self):
        """All provide-collisions detected across the indexed features."""
        return self._load_index().get("collisions") or []

    def collisions_for(self, short):
        """Collisions that involve the given feature short name."""
        return [c for c in self.collisions() if short in (c.get("features") or [])]

    def archetypes(self):
        """Distinct archetypes present in the index (for filter controls)."""
        return sorted({f.get("archetype") for f in self.all_features() if f.get("archetype")})

    def categories(self):
        """Distinct categories present in the index (for filter controls)."""
        return sorted({f.get("category") for f in self.all_features() if f.get("category")})
